services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick
script:
  - docker build -t lernstick-maven .
  - mkdir /tmp/smoke && docker run -v /tmp/smoke:/tmp/smoke lernstick-maven:latest
  - ./smoke-test/smoke-test.sh  
